"""create complaints table

Revision ID: 1af110b89527
Revises: e1c11019ad6c
Create Date: 2026-08-23 00:56:15.926469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1af110b89527'
down_revision: Union[str, None] = 'e1c11019ad6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resident_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('Plumbing', 'Electrical', 'Cleanliness', 'Security', 'Parking', 'Other', name='complaintcategory'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('Open', 'In Progress', 'Resolved', name='complaintstatus'), nullable=False),
    sa.Column('priority', sa.Enum('Low', 'Medium', 'High', name='complaintpriority'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resident_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaints_id'), 'complaints', ['id'], unique=False)
    op.create_index(op.f('ix_complaints_resident_id'), 'complaints', ['resident_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_complaints_resident_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_id'), table_name='complaints')
    op.drop_table('complaints')
    # ### end Alembic commands ###
