"""create app_settings table

Revision ID: 5e5821a5b86c
Revises: b1d19ff55b65
Create Date: 2026-08-23 01:01:20.869586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e5821a5b86c'
down_revision: Union[str, None] = 'b1d19ff55b65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_app_settings_key'), 'app_settings', ['key'], unique=False)
    # ### end Alembic commands ###
    from datetime import datetime, timezone
    app_settings_table = sa.table(
        'app_settings',
        sa.column('key', sa.String),
        sa.column('value', sa.Text),
        sa.column('description', sa.Text),
        sa.column('updated_at', sa.DateTime),
    )
    op.bulk_insert(app_settings_table, [
        {
            'key': 'overdue_threshold_days',
            'value': '7',
            'description': 'Threshold in days after which an open complaint is considered overdue',
            'updated_at': datetime.now(timezone.utc),
        }
    ])



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_settings_key'), table_name='app_settings')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
